// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kmxeoedzqbctsqbwvyql.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtteGVvZWR6cWJjdHNxYnd2eXFsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MzU5MTAsImV4cCI6MjA2NTUxMTkxMH0.I3abyLT0AffBGkiaK-b8SG2D1m10T5__1rYSsJXPCwE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);